# Generated by Django 3.2.18 on 2023-04-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
